name: Deploy Blog to GitHub Pages
on:
  push:
    branches:
      - main  # 推送到 main 分支时触发

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Set Git encoding
        run: |
          git config --global core.quotepath false
          git config --global i18n.commitEncoding utf-8
          git config --global i18n.logOutputEncoding utf-8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG_SECRET_TOKEN }}
          publish_dir: ./out
          # 添加目标分支
          publish_branch: pages
